#!/bin/bash
# AWS Academy Learner Lab Setup Script
# This script helps configure Terraform for AWS Academy Learner Lab environment
# 
# Usage:
#   1. Copy your AWS Learner Lab credentials
#   2. Run: bash terraform/setup-aws-lab-credentials.sh
#   3. Or manually export the environment variables shown below

echo "AWS Academy Learner Lab - Terraform Setup"
echo "=========================================="
echo ""
echo "Please follow these steps to configure your AWS credentials:"
echo ""
echo "1. Log into AWS Academy Learner Lab"
echo "2. Click 'AWS Details' button"
echo "3. Click 'Show' under AWS CLI"
echo "4. Copy the displayed credentials"
echo ""
echo "5. Create/Edit the file: ~/.aws/credentials.lab"
echo "   And paste the credentials in the following format:"
echo ""
echo "[aws-academy-lab]"
echo "aws_access_key_id = YOUR_ACCESS_KEY"
echo "aws_secret_access_key = YOUR_SECRET_KEY"
echo "aws_session_token = YOUR_SESSION_TOKEN"
echo ""
echo "6. Then you can use the following commands:"
echo ""
echo "   # Option A: Export environment variables"
echo "   export AWS_ACCESS_KEY_ID='YOUR_ACCESS_KEY'"
echo "   export AWS_SECRET_ACCESS_KEY='YOUR_SECRET_KEY'"
echo "   export AWS_SESSION_TOKEN='YOUR_SESSION_TOKEN'"
echo "   export AWS_DEFAULT_REGION='us-east-1'"
echo ""
echo "   # Option B: Use AWS profile"
echo "   export AWS_PROFILE=aws-academy-lab"
echo "   export AWS_DEFAULT_REGION=us-east-1"
echo ""
echo "   # Option C: Configure AWS CLI"
echo "   aws configure --profile aws-academy-lab"
echo ""
echo "7. Verify credentials are working:"
echo "   aws sts get-caller-identity"
echo ""
echo "8. Deploy Terraform:"
echo "   cd terraform"
echo "   terraform init"
echo "   terraform plan"
echo "   terraform apply"
echo ""
echo "IMPORTANT NOTES:"
echo "==============="
echo "- AWS Academy Learner Lab sessions expire (typically 4 hours)"
echo "- You'll need new credentials for each new session"
echo "- Session tokens are temporary and region-specific"
echo "- Always verify credentials before running terraform apply"
echo "- The region MUST be us-east-1 (as configured in this lab)"
echo ""
